version: '3.8'
services:
  web:
    build:
      context: .
    container_name: nest_prod_test
    ports:
      - 3001:3000
      - 9229:9229
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm run start:dev"

  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   restart: always
  #   command:
  #     - '--character-set-server=utf8mb4'
  #     - '--collation-server=utf8mb4_unicode_ci'
  #     - '--default-authentication-plugin=mysql_native_password'
  #     - '--event_scheduler=ON'
  #   ports:
  #     - 3336:3306
  #   volumes:
  #     - ./mysqldb/init:/docker-entrypoint-initdb.d
  #     - ./mysqldb/data:/var/lib/mysql
  #     - ./mysqldb/backup:/backup
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ladolcevita2023